
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer yymml_create_buffer
#define yy_delete_buffer yymml_delete_buffer
#define yy_flex_debug yymml_flex_debug
#define yy_init_buffer yymml_init_buffer
#define yy_flush_buffer yymml_flush_buffer
#define yy_load_buffer_state yymml_load_buffer_state
#define yy_switch_to_buffer yymml_switch_to_buffer
#define yyin yymmlin
#define yyleng yymmlleng
#define yylex yymmllex
#define yylineno yymmllineno
#define yyout yymmlout
#define yyrestart yymmlrestart
#define yytext yymmltext
#define yywrap yymmlwrap
#define yyalloc yymmlalloc
#define yyrealloc yymmlrealloc
#define yyfree yymmlfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yymmlrestart(yymmlin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yymmlleng;

extern FILE *yymmlin, *yymmlout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yymmltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yymmltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yymmlrestart()), so that the user can continue scanning by
	 * just pointing yymmlin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yymmltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yymmlleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yymmlwrap()'s to do buffer switches
 * instead of setting up a fresh yymmlin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yymmlrestart (FILE *input_file  );
void yymml_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yymml_create_buffer (FILE *file,int size  );
void yymml_delete_buffer (YY_BUFFER_STATE b  );
void yymml_flush_buffer (YY_BUFFER_STATE b  );
void yymmlpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yymmlpop_buffer_state (void );

static void yymmlensure_buffer_stack (void );
static void yymml_load_buffer_state (void );
static void yymml_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yymml_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yymml_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yymml_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yymml_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yymmlalloc (yy_size_t  );
void *yymmlrealloc (void *,yy_size_t  );
void yymmlfree (void *  );

#define yy_new_buffer yymml_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yymmlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yymml_create_buffer(yymmlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yymmlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yymml_create_buffer(yymmlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yymmlin = (FILE *) 0, *yymmlout = (FILE *) 0;

typedef int yy_state_type;

extern int yymmllineno;

int yymmllineno = 1;

extern char *yymmltext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yymmltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yymmltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yymmlleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[360] =
    {   0,
        0,    0,   85,   83,   82,   73,   83,   83,   76,   77,
       78,   74,   75,   70,   83,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   71,   72,   82,
        0,    0,   78,    0,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   58,   78,   78,   78,   78,   78,   49,   78,   78,
       78,   78,   14,   78,   78,   78,   78,   78,   78,   78,
       78,   13,   78,   10,   78,   78,   78,   78,   78,   78,

       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   49,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   10,   78,   78,   78,   78,
       78,   79,   81,    0,   78,   78,   78,   78,   43,   78,
       78,   78,   47,   64,   65,   62,   78,   78,   37,   78,
       78,   78,   78,   78,   78,   20,   21,   78,   78,   48,
       78,   78,   78,   12,   78,   78,   78,   78,   22,   23,
       78,   78,   15,   78,   78,   41,   78,   78,    5,   78,
       78,   78,   78,   78,   78,   43,   78,   78,   78,   64,

       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,    5,   78,   78,    0,   54,   78,   78,
       55,   42,   45,   57,   46,   78,   78,   27,    3,   78,
       18,    1,   50,    6,   78,   78,   78,   24,   78,   78,
       78,   78,   78,   19,   78,   78,   78,   78,   78,   78,
       67,   78,   78,   78,   61,   25,   78,   78,   57,   78,
       78,   27,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       80,   56,   28,   78,   78,   78,   33,   36,   78,   78,

       78,   78,   44,    9,   53,   69,   51,   78,   78,   78,
       78,   66,    2,   78,   29,   78,   78,   78,   78,   78,
       78,   78,   78,    9,   53,   78,   78,   78,   78,   78,
       29,   78,   60,   59,   78,   68,   78,   26,   30,    4,
       31,   34,   52,   40,   11,    8,    7,   17,   32,   35,
       16,   78,   78,   38,   39,   78,   78,   63,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    1,    1,    5,
        5,    1,    1,    8,    9,   10,   10,   10,   11,   12,
       13,   10,   10,   10,   14,   10,   10,   15,   16,    1,
       17,    1,    1,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   10,   10,   28,   29,   30,   31,   32,
       10,   33,   34,   35,   36,   10,   37,   10,   38,   10,
        1,   10,    1,    1,   10,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   10,   10,   48,   49,   50,
       51,   52,   10,   53,   54,   55,   56,   10,   57,   10,
       58,   10,   59,    1,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[61] =
    {   0,
        1,    2,    3,    2,    2,    1,    1,    1,    1,    4,
        4,    4,    4,    4,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[364] =
    {   0,
        0,    0,  437,  438,   59,  438,    0,    0,  438,  438,
        0,  438,  438,  438,  418,  405,   40,   53,   41,  402,
      410,   57,   39,   60,   61,  395,   64,   73,   74,   65,
      397,  380,   62,   75,   72,  377,  385,   81,   74,   86,
       89,  370,   88,   86,  103,   90,  372,  438,  438,   63,
      419,  421,    0,    0,  387,  399,  390,  384,  398,  384,
      389,  388,  388,  393,  391,  378,   79,  378,  116,  383,
      381,    0,  374,  383,  374,  375,  128,  377,  375,  380,
      380,  365,    0,  369,  367,  370,  366,  363,  364,  366,
      371,    0,  357,  355,  132,  133,  359,  356,  364,  330,

      342,  333,  327,  341,  327,  332,  331,  331,  336,  334,
      321,  105,  321,  112,  326,  324,  317,  326,  317,  318,
      115,  320,  318,  323,  323,  308,  312,  310,  313,  309,
      306,  307,  309,  314,  300,  298,  125,  121,  302,  299,
      307,  438,  438,  346,  319,  313,  324,  316,  317,  316,
      314,  313,    0,  313,    0,    0,  316,  303,    0,  305,
      317,  313,  302,  306,  301,    0,    0,  310,  299,    0,
      308,  305,  293,    0,  292,  295,  294,  298,    0,    0,
      300,  289,    0,  282,  145,    0,  134,  287,  149,  295,
      284,  267,  261,  272,  264,  265,  264,  262,  261,  261,

      264,  251,  253,  265,  261,  250,  254,  249,  258,  247,
      256,  253,  241,  240,  243,  242,  246,  248,  237,  230,
      130,  126,  235,  139,  243,  232,  282,    0,  248,  259,
        0,    0,    0,  258,    0,  250,  244,  171,    0,  243,
        0,    0,    0,    0,  246,  245,  245,    0,  242,  241,
      249,  236,  247,    0,  248,  236,  236,  235,  230,  230,
        0,  232,  240,  230,    0,    0,  205,  216,  215,  207,
      201,  173,  200,  203,  202,  202,  199,  198,  206,  193,
      204,  205,  193,  193,  192,  187,  187,  189,  197,  187,
      438,    0,    0,  166,  216,  213,    0,    0,  208,  204,

      201,  208,    0,  178,  204,    0,    0,  206,  206,  198,
      206,    0,    0,  196,  180,  204,  151,  183,  180,  175,
      171,  168,  175,  183,  171,  173,  173,  164,  169,  156,
      185,  157,    0,    0,  189,    0,  143,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  191,  117,    0,    0,   80,   46,    0,  438,  203,
      207,   77,  211
    } ;

static yyconst flex_int16_t yy_def[364] =
    {   0,
      359,    1,  359,  359,  359,  359,  360,  361,  359,  359,
      362,  359,  359,  359,  359,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  359,  359,  359,
      360,  361,  362,  363,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  359,  359,  363,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  359,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      359,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,    0,  359,
      359,  359,  359
    } ;

static yyconst flex_uint16_t yy_nxt[499] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       11,   11,   11,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   11,   11,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   11,   11,   32,   33,
       34,   35,   36,   11,   11,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   11,   11,   48,   49,
       50,   56,   50,   67,   50,   75,   50,   68,   57,   58,
       76,   61,   77,   59,   60,   62,   69,   63,   72,   64,
       53,   65,   78,   82,   66,   73,   74,   83,   79,   85,
       80,   87,   90,   81,   91,  358,   86,   97,  121,   88,

       92,   93,   98,  101,   89,   94,  157,   95,   96,  358,
      102,  103,  158,  106,  112,  104,  105,  107,  113,  108,
      119,  109,   72,  110,  130,  120,  111,  114,  122,  117,
      118,  126,  131,  128,  123,   83,  124,  132,  221,  125,
      129,  133,  139,  134,  160,  185,  168,  140,  161,   92,
      135,  187,  201,  209,  136,  169,  137,  138,  202,  222,
      203,  186,  210,  188,  204,  257,  259,  357,  260,  262,
      284,  223,  258,  356,  186,  263,  264,  285,  286,  288,
      287,  297,  298,  297,  298,  289,  290,  333,  341,  342,
      349,  350,  333,  341,  342,  349,  350,  351,  334,  354,

      355,  354,  355,  334,   51,  348,   51,   52,   52,  347,
       52,  144,  144,  346,  144,  345,  344,  343,  340,  339,
      338,  353,  336,  352,  351,  348,  347,  346,  345,  344,
      343,  340,  339,  338,  337,  336,  335,  332,  331,  330,
      313,  312,  329,  328,  327,  326,  307,  306,  325,  324,
      303,  323,  322,  321,  320,  319,  318,  317,  293,  292,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  296,  295,
      294,  293,  292,  291,  266,  265,  261,  283,  282,  254,
      281,  280,  279,  278,  277,  248,  276,  275,  274,  244,

      243,  242,  241,  273,  239,  272,  271,  270,  235,  269,
      233,  232,  231,  268,  267,  228,  266,  265,  261,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  220,  183,  219,  218,  180,  179,  217,  216,
      215,  214,  174,  213,  212,  211,  170,  167,  166,  208,
      207,  206,  205,  159,  156,  155,  200,  153,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,

      173,  172,  171,  170,  167,  166,  165,  164,  163,  162,
      159,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  143,  142,  141,  127,  116,  115,  100,
       99,   84,   71,   70,   55,   54,  359,    3,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359

    } ;

static yyconst flex_int16_t yy_chk[499] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,   17,    5,   19,   50,   23,   50,   19,   17,   17,
       23,   18,   24,   17,   17,   18,   19,   18,   22,   18,
      362,   18,   24,   25,   18,   22,   22,   25,   24,   27,
       24,   28,   29,   24,   29,  357,   27,   30,   40,   28,

       29,   29,   30,   33,   28,   29,   67,   29,   29,  356,
       33,   33,   67,   34,   35,   33,   33,   34,   35,   34,
       39,   34,   38,   34,   44,   39,   34,   35,   40,   38,
       38,   41,   44,   43,   40,   41,   40,   44,  137,   40,
       43,   45,   46,   45,   69,   95,   77,   46,   69,   45,
       45,   96,  112,  121,   45,   77,   45,   45,  112,  138,
      114,   95,  121,   96,  114,  185,  187,  353,  187,  189,
      221,  138,  185,  337,  137,  189,  189,  221,  222,  224,
      222,  238,  238,  272,  272,  224,  224,  294,  304,  304,
      315,  315,  317,  324,  324,  331,  331,  332,  294,  335,

      335,  352,  352,  317,  360,  330,  360,  361,  361,  329,
      361,  363,  363,  328,  363,  327,  326,  325,  323,  322,
      321,  320,  319,  318,  316,  314,  311,  310,  309,  308,
      305,  302,  301,  300,  299,  296,  295,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  271,  270,  269,  268,  267,
      264,  263,  262,  260,  259,  258,  257,  256,  255,  253,
      252,  251,  250,  249,  247,  246,  245,  240,  237,  236,
      234,  230,  229,  227,  226,  225,  223,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,

      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  188,  184,
      182,  181,  178,  177,  176,  175,  173,  172,  171,  169,
      168,  165,  164,  163,  162,  161,  160,  158,  157,  154,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  141,
      140,  139,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  120,  119,  118,
      117,  116,  115,  113,  111,  110,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   94,
       93,   91,   90,   89,   88,   87,   86,   85,   84,   82,

       81,   80,   79,   78,   76,   75,   74,   73,   71,   70,
       68,   66,   65,   64,   63,   62,   61,   60,   59,   58,
       57,   56,   55,   52,   51,   47,   42,   37,   36,   32,
       31,   26,   21,   20,   16,   15,    3,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yymml_flex_debug;
int yymml_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yymmltext;
#line 1 "modules/axe/mml/parser_l"
#line 2 "modules/axe/mml/parser_l"
#include "modules/common.h"
#include "modules/nethelper.h"
#include "modules/axe/mml/parser.h" 
#include "modules/axe/mml/parser.y.tab.h" 

// Lex/yacc part

void yyerror(char *s) {
    fprintf(stdout, "MML PARSER YYERROR: <%s>\n", s);
}

int myyymmlinput(char *buf, int max_size)
{
	size_t nb_bytes = 0;

	if (yyinput_analyse_stop0_file1_buffer2 == 2) {
		int read_buffer_index = STS_COUNTER_VALUE(sts_netcs_transport_receive, NetCS_DataSet[yyinput_analyse_buffer_set].transport_receive.read);
		int strlength = NetCS_DataSet[yyinput_analyse_buffer_set].transport_receive.buffer[read_buffer_index].size;
		nb_bytes = ((strlength>max_size)? max_size:strlength);

		ErrorTraceHandle(3, "myyymmlinput(buffer) %d, %d, %d\n", yyinput_analyse_buffer_set, read_buffer_index, strlength);

		if (nb_bytes)
			memcpy(buf, NetCS_DataSet[yyinput_analyse_buffer_set].transport_receive.buffer[read_buffer_index].data, nb_bytes);
		else
			buf[0] = '\0';
	} else if (yyinput_analyse_stop0_file1_buffer2 == 1) { // input from file
		nb_bytes = PrimitiveFile2Buffer("./",
										"sigtran.config",
										buf,
										max_size);
		ErrorTraceHandle(3, "myyymmlinput(file) <%s> size=%d\n\n", buf, nb_bytes);
	}

	yyinput_analyse_stop0_file1_buffer2 = 0;
	return (int) nb_bytes;
}

#define YY_INPUT(buf,result,max_size) { result = myyymmlinput(buf, max_size); }

/* Start Conditions */
/* Action Keywords */
#line 756 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yymmllex_destroy (void );

int yymmlget_debug (void );

void yymmlset_debug (int debug_flag  );

YY_EXTRA_TYPE yymmlget_extra (void );

void yymmlset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yymmlget_in (void );

void yymmlset_in  (FILE * _in_str  );

FILE *yymmlget_out (void );

void yymmlset_out  (FILE * _out_str  );

yy_size_t yymmlget_leng (void );

char *yymmlget_text (void );

int yymmlget_lineno (void );

void yymmlset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yymmlwrap (void );
#else
extern int yymmlwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yymmltext, yymmlleng, 1, yymmlout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yymmlin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yymmlin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yymmlin))==0 && ferror(yymmlin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yymmlin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yymmllex (void);

#define YY_DECL int yymmllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yymmltext and yymmlleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yymmlin )
			yymmlin = stdin;

		if ( ! yymmlout )
			yymmlout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yymmlensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yymml_create_buffer(yymmlin,YY_BUF_SIZE );
		}

		yymml_load_buffer_state( );
		}

	{
#line 146 "modules/axe/mml/parser_l"


#line 977 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yymmltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 360 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 438 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 148 "modules/axe/mml/parser_l"
return tokHELP;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 149 "modules/axe/mml/parser_l"
return tokSTATS;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 150 "modules/axe/mml/parser_l"
return tokDUMP;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 152 "modules/axe/mml/parser_l"
return tokMMLCNF;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 153 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokTRN; };
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 154 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokINFO; };
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 156 "modules/axe/mml/parser_l"
return tokSS7LOC;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 157 "modules/axe/mml/parser_l"
return tokSS7CON;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 158 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokOWNSP; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 159 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokSP; 	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 160 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokSPTYPE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 161 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokNET; 	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 162 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokSI; 	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 163 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokNI; 	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 164 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokSLS; 	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 166 "modules/axe/mml/parser_l"
return tokTRNLOC;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 167 "modules/axe/mml/parser_l"
return tokTRNCON;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 168 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokEPID; 	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 169 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokSAID; 	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 170 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokLIP; 	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 171 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokLPN; 	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 172 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokRIP; 	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 173 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokRPN; 	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 174 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokMODE; 	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 175 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokUSER; 	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 177 "modules/axe/mml/parser_l"
return tokM3ACON;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 178 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokDEST; 	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 179 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokBMODE;	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 180 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokTRNID; 	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 182 "modules/axe/mml/parser_l"
return tokM3LOOP;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 183 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokOWNSP1; 	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 184 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokTRNID1; 	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 185 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokDEST1; 	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 186 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokOWNSP2; 	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 187 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokTRNID2; 	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 188 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokDEST2; 	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 189 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokDIR; 	 	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 190 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCICINC1; 	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 191 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCICINC2; 	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 193 "modules/axe/mml/parser_l"
return tokSCCPCF;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 194 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokSSN; 	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 196 "modules/axe/mml/parser_l"
return tokBSCI;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 197 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokBSC; 	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 198 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokMSCSP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 200 "modules/axe/mml/parser_l"
return tokBTSI;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 201 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCELL; 	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 202 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCGI; 	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 204 "modules/axe/mml/parser_l"
return tokMEI;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 205 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokME; 	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 206 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokIMSI; 	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 207 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokRANGE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 209 "modules/axe/mml/parser_l"
return tokPHONEI;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 210 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokPHONE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 211 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokANUM; 	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 212 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokBNUM; 	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 213 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokBDEST; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 215 "modules/axe/mml/parser_l"
return tokCALL;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 216 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokID; 	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 217 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCALLER;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 218 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCALLED;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 219 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokTYPE;	}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 220 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCPS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 221 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokDURATION; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 222 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCIC; 	}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 224 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return tokCMD; 	}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 226 "modules/axe/mml/parser_l"
return tokSTART;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 227 "modules/axe/mml/parser_l"
return tokSTOP;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 228 "modules/axe/mml/parser_l"
return tokDELETE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 229 "modules/axe/mml/parser_l"
return tokPRINT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 233 "modules/axe/mml/parser_l"
return EQUAL;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 234 "modules/axe/mml/parser_l"
return LBRACE;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 235 "modules/axe/mml/parser_l"
return RBRACE;
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 236 "modules/axe/mml/parser_l"
return NEWLINE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 237 "modules/axe/mml/parser_l"
return DOTDOT;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 238 "modules/axe/mml/parser_l"
return DOTCOMMA;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 239 "modules/axe/mml/parser_l"
return COMMA;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 240 "modules/axe/mml/parser_l"
return MINUS;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 243 "modules/axe/mml/parser_l"
{ yylval.strVal=(char*)strdup(yymmltext); return STRING; 	}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 244 "modules/axe/mml/parser_l"
{ 
				// remove quotes
				yylval.strVal=(char*)strdup(yymmltext+sizeof(char));
				yylval.strVal[strlen(yylval.strVal)-1] = '\0';
				return STRING;
			}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 250 "modules/axe/mml/parser_l"
{ 
				// skip @@
				yylval.strVal=(char*)strdup(yymmltext+2*sizeof(char));
				yylval.strVal[strlen(yylval.strVal)-1] = '\0';
				return TRACE;
			}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 256 "modules/axe/mml/parser_l"
{ 
				// skip #
				yylval.strVal=(char*)strdup(yymmltext+sizeof(char));
				yylval.strVal[strlen(yylval.strVal)-1] = '\0';
				return COMMENTED;
			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 263 "modules/axe/mml/parser_l"
{ /* Do nothing - ignore input */ }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 264 "modules/axe/mml/parser_l"
{ /* Do nothing - ignore input */ }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 267 "modules/axe/mml/parser_l"
ECHO;
	YY_BREAK
#line 1472 "<stdout>"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yymmlin at a new source and called
			 * yymmllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yymmlin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yymmlwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yymmltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yymmllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yymmlrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yymmlrestart(yymmlin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yymmlrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 360 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 360 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 359);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yymmltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yymmlrestart(yymmlin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yymmlwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yymmltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yymmlrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yymmlensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yymml_create_buffer(yymmlin,YY_BUF_SIZE );
	}

	yymml_init_buffer(YY_CURRENT_BUFFER,input_file );
	yymml_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yymml_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yymmlpop_buffer_state();
	 *		yymmlpush_buffer_state(new_buffer);
     */
	yymmlensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yymml_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yymmlwrap()) processing, but the only time this flag
	 * is looked at is after yymmlwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yymml_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yymmlin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yymml_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yymmlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yymml_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yymmlalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yymml_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yymml_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yymml_create_buffer()
 * 
 */
    void yymml_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yymmlfree((void *) b->yy_ch_buf  );

	yymmlfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yymmlrestart() or at EOF.
 */
    static void yymml_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yymml_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yymml_init_buffer was _probably_
     * called from yymmlrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yymml_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yymml_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yymmlpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yymmlensure_buffer_stack();

	/* This block is copied from yymml_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yymml_switch_to_buffer. */
	yymml_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yymmlpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yymml_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yymml_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yymmlensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yymmlalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yymmlensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yymmlrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yymmlensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yymml_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yymmlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yymml_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yymml_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yymmllex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yymml_scan_bytes() instead.
 */
YY_BUFFER_STATE yymml_scan_string (yyconst char * yystr )
{
    
	return yymml_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yymmllex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yymml_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yymmlalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yymml_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yymml_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yymml_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yymmltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yymmltext[yymmlleng] = (yy_hold_char); \
		(yy_c_buf_p) = yymmltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yymmlleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yymmlget_lineno  (void)
{
        
    return yymmllineno;
}

/** Get the input stream.
 * 
 */
FILE *yymmlget_in  (void)
{
        return yymmlin;
}

/** Get the output stream.
 * 
 */
FILE *yymmlget_out  (void)
{
        return yymmlout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yymmlget_leng  (void)
{
        return yymmlleng;
}

/** Get the current token.
 * 
 */

char *yymmlget_text  (void)
{
        return yymmltext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yymmlset_lineno (int  _line_number )
{
    
    yymmllineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yymml_switch_to_buffer
 */
void yymmlset_in (FILE *  _in_str )
{
        yymmlin = _in_str ;
}

void yymmlset_out (FILE *  _out_str )
{
        yymmlout = _out_str ;
}

int yymmlget_debug  (void)
{
        return yymml_flex_debug;
}

void yymmlset_debug (int  _bdebug )
{
        yymml_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yymmllex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yymmlin = stdin;
    yymmlout = stdout;
#else
    yymmlin = (FILE *) 0;
    yymmlout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yymmllex_init()
     */
    return 0;
}

/* yymmllex_destroy is for both reentrant and non-reentrant scanners. */
int yymmllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yymml_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yymmlpop_buffer_state();
	}

	/* Destroy the stack itself. */
	yymmlfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yymmllex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yymmlalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yymmlrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yymmlfree (void * ptr )
{
			free( (char *) ptr );	/* see yymmlrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 267 "modules/axe/mml/parser_l"



int yymmlwrap(void) { 
    return 1; 
}

